### ISSUE TITLE
Ortho-K to-do-list

### ISSUE THREAD

**Issue by ielecer** [ielecer/CNN_Accelerator#3]
- [x] Transplant current CNN to adapt Ortho-K algorithm for forward-propagation.
- [x] Improve and accelerate algorithm from HLS level.
- [ ] Build and test SoC for Ortho-K.
- [ ] Add back-propagation algorithm IP into SoC for CNN training stage.
